// NanoRPC Protocol Definition - Lightweight RPC for Embedded Systems
//
// NanoRPC is designed for resource-constrained embedded systems operating in
// trusted environments. It provides efficient RPC capabilities with minimal
// overhead for serial communications and local network connections.
//
// Key features:
// - Minimal memory footprint optimised for microcontrollers
// - Efficient binary encoding using Protocol Buffers with nanopb
// - Hash-based path routing using 32-bit FNV-1a hashes
// - Support for request-response patterns and publish-subscribe messaging
// - Automatic reconnection handling
// - Gateway-friendly design for translation to gRPC/HTTP2
//
// Wire Format:
// Each message uses length-delimited Protocol Buffer encoding compatible
// with Google's protodelim package:
// ┌─────────────────┬─────────────────────────┐
// │ Length (varint) │ Protobuf Encoded Data   │
// └─────────────────┴─────────────────────────┘
//
// Length Prefix (Protocol Buffer varint encoding):
// - Values 0-127: 1 byte
// - Values 128-16383: 2 bytes
// - Larger values: 3+ bytes
// - Protocol overhead: 2-6 bytes for length prefix per message
//
// Message Flow Patterns:
//
// 1. Ping/Pong (Health Check):
//    Client: TYPE_PING (request_id=1)
//    Server: TYPE_PONG (request_id=1, status=OK)
//
// 2. Request/Response (RPC Call):
//    Client: TYPE_REQUEST (request_id=42, path="/api/get", data="query")
//    Server: TYPE_RESPONSE (request_id=42, status=OK, data="result")
//
// 3. Subscribe/Update (Pub-Sub):
//    Client: TYPE_SUBSCRIBE (request_id=100, path="/sensors/temp", data={min:25})
//    Server: TYPE_RESPONSE (request_id=100, status=OK)  // Acknowledgement
//    Server: TYPE_UPDATE (request_id=100, data={value:26.5})  // Updates...
//
// 4. Unsubscribe:
//    Client: TYPE_REQUEST (request_id=100, path="/sensors/temp", data="")  // Same request_id as subscription!
//    Server: TYPE_RESPONSE (request_id=100, status=OK)
//
// Subscription Semantics:
// - Unsubscribe MUST use the same request_id as the original subscription
// - Empty data in TYPE_SUBSCRIBE means receive all updates (unconditional)
// - Non-empty data provides handler-specific filter criteria
// - All subscriptions are automatically removed when session disconnects
//
// Path Resolution:
// - String paths (e.g., "/api/temperature") for human readability
// - Hash paths (FNV-1a 32-bit) for efficiency in resource-constrained environments
// - Bidirectional hash cache maintained by both client and server
//
// FNV-1a Hash Algorithm (32-bit):
//   hash = 2166136261 (0x811c9dc5)  // FNV-1a offset basis
//   for each byte in path:
//     hash = hash XOR byte
//     hash = hash × 16777619 (0x01000193)  // FNV prime
//   return hash
//
// IMPORTANT: This is FNV-1a (XOR then multiply), not FNV-1 (multiply then XOR).
// Hash collisions are detected and reported as errors during handler registration.
//
// Deployment Context:
// - Designed for trusted environments (serial, local networks)
// - NOT intended for public internet exposure
// - Use gateway pattern for internet connectivity: Device ↔ NanoRPC ↔ Gateway ↔ gRPC/HTTP2 ↔ Cloud
//
// Error Handling:
// ┌─────────────────────────┬──────────────────────────┐
// │ Condition               │ Response Status          │
// ├─────────────────────────┼──────────────────────────┤
// │ Unknown path            │ STATUS_NOT_FOUND         │
// │ Hash collision          │ STATUS_INTERNAL_ERROR    │
// │ Handler error           │ STATUS_INTERNAL_ERROR    │
// │ Invalid message         │ Connection closed        │
// └─────────────────────────┴──────────────────────────┘
//
// Delivery Guarantees:
// - Requests: Guaranteed response (success or error)
// - Updates: Best-effort delivery, no acknowledgement required
// - Ordering: Updates maintain send order per subscription
// - Concurrency: Thread-safe publishing allows concurrent updates
//
// See NANORPC_PROTOCOL.md for complete protocol specification.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: nanorpc.proto

package nanorpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	_ "protomcp.org/nanorpc/pkg/nanopb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NanoRPCRequest_Type int32

const (
	NanoRPCRequest_TYPE_UNSPECIFIED NanoRPCRequest_Type = 0 // Invalid/unset request type
	NanoRPCRequest_TYPE_PING        NanoRPCRequest_Type = 1 // Health check request
	NanoRPCRequest_TYPE_REQUEST     NanoRPCRequest_Type = 2 // RPC call or unsubscribe (empty data)
	NanoRPCRequest_TYPE_SUBSCRIBE   NanoRPCRequest_Type = 3 // Subscribe to updates with optional filter
)

// Enum value maps for NanoRPCRequest_Type.
var (
	NanoRPCRequest_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PING",
		2: "TYPE_REQUEST",
		3: "TYPE_SUBSCRIBE",
	}
	NanoRPCRequest_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PING":        1,
		"TYPE_REQUEST":     2,
		"TYPE_SUBSCRIBE":   3,
	}
)

func (x NanoRPCRequest_Type) Enum() *NanoRPCRequest_Type {
	p := new(NanoRPCRequest_Type)
	*p = x
	return p
}

func (x NanoRPCRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NanoRPCRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_nanorpc_proto_enumTypes[0].Descriptor()
}

func (NanoRPCRequest_Type) Type() protoreflect.EnumType {
	return &file_nanorpc_proto_enumTypes[0]
}

func (x NanoRPCRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NanoRPCRequest_Type.Descriptor instead.
func (NanoRPCRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_nanorpc_proto_rawDescGZIP(), []int{0, 0}
}

type NanoRPCResponse_Type int32

const (
	NanoRPCResponse_TYPE_UNSPECIFIED NanoRPCResponse_Type = 0 // Invalid/unset response type
	NanoRPCResponse_TYPE_PONG        NanoRPCResponse_Type = 1 // Ping response
	NanoRPCResponse_TYPE_RESPONSE    NanoRPCResponse_Type = 2 // RPC response or subscription acknowledgement
	NanoRPCResponse_TYPE_UPDATE      NanoRPCResponse_Type = 3 // Subscription update
)

// Enum value maps for NanoRPCResponse_Type.
var (
	NanoRPCResponse_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PONG",
		2: "TYPE_RESPONSE",
		3: "TYPE_UPDATE",
	}
	NanoRPCResponse_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PONG":        1,
		"TYPE_RESPONSE":    2,
		"TYPE_UPDATE":      3,
	}
)

func (x NanoRPCResponse_Type) Enum() *NanoRPCResponse_Type {
	p := new(NanoRPCResponse_Type)
	*p = x
	return p
}

func (x NanoRPCResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NanoRPCResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_nanorpc_proto_enumTypes[1].Descriptor()
}

func (NanoRPCResponse_Type) Type() protoreflect.EnumType {
	return &file_nanorpc_proto_enumTypes[1]
}

func (x NanoRPCResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NanoRPCResponse_Type.Descriptor instead.
func (NanoRPCResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_nanorpc_proto_rawDescGZIP(), []int{1, 0}
}

type NanoRPCResponse_Status int32

const (
	NanoRPCResponse_STATUS_UNSPECIFIED    NanoRPCResponse_Status = 0 // Invalid/unset status
	NanoRPCResponse_STATUS_OK             NanoRPCResponse_Status = 1 // Success
	NanoRPCResponse_STATUS_NOT_FOUND      NanoRPCResponse_Status = 2 // Path/handler not found
	NanoRPCResponse_STATUS_NOT_AUTHORIZED NanoRPCResponse_Status = 3 // Authorisation failure
	NanoRPCResponse_STATUS_INTERNAL_ERROR NanoRPCResponse_Status = 4 // Server error
)

// Enum value maps for NanoRPCResponse_Status.
var (
	NanoRPCResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_NOT_FOUND",
		3: "STATUS_NOT_AUTHORIZED",
		4: "STATUS_INTERNAL_ERROR",
	}
	NanoRPCResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":    0,
		"STATUS_OK":             1,
		"STATUS_NOT_FOUND":      2,
		"STATUS_NOT_AUTHORIZED": 3,
		"STATUS_INTERNAL_ERROR": 4,
	}
)

func (x NanoRPCResponse_Status) Enum() *NanoRPCResponse_Status {
	p := new(NanoRPCResponse_Status)
	*p = x
	return p
}

func (x NanoRPCResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NanoRPCResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_nanorpc_proto_enumTypes[2].Descriptor()
}

func (NanoRPCResponse_Status) Type() protoreflect.EnumType {
	return &file_nanorpc_proto_enumTypes[2]
}

func (x NanoRPCResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NanoRPCResponse_Status.Descriptor instead.
func (NanoRPCResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_nanorpc_proto_rawDescGZIP(), []int{1, 1}
}

// NanoRPC request message supporting three primary patterns:
// 1. Ping/Pong: Connection health checking
// 2. Request/Response: RPC calls with guaranteed responses
// 3. Subscribe/Update: Publish-subscribe for real-time data
type NanoRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for request/response correlation.
	// Must be unique per session to match responses.
	// For subscriptions, updates will use the same request_id.
	RequestId int32 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Type of request operation to perform.
	RequestType NanoRPCRequest_Type `protobuf:"varint,2,opt,name=request_type,json=requestType,proto3,enum=NanoRPCRequest_Type" json:"request_type,omitempty"`
	// Path identification using either string or hash for efficiency.
	// Hash paths use 32-bit FNV-1a algorithm for minimal overhead.
	// Both client and server maintain bidirectional hash caches.
	//
	// Types that are assignable to PathOneof:
	//
	//	*NanoRPCRequest_PathHash
	//	*NanoRPCRequest_Path
	PathOneof isNanoRPCRequest_PathOneof `protobuf_oneof:"path_oneof"`
	// Request payload data. Usage varies by request type:
	// - TYPE_PING: unused (should be empty)
	// - TYPE_REQUEST: RPC parameters or empty for unsubscribe
	// - TYPE_SUBSCRIBE: filter criteria or empty for all updates
	// Uses nanopb callback type for zero-copy handling on embedded systems.
	Data []byte `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NanoRPCRequest) Reset() {
	*x = NanoRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanorpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NanoRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NanoRPCRequest) ProtoMessage() {}

func (x *NanoRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nanorpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NanoRPCRequest.ProtoReflect.Descriptor instead.
func (*NanoRPCRequest) Descriptor() ([]byte, []int) {
	return file_nanorpc_proto_rawDescGZIP(), []int{0}
}

func (x *NanoRPCRequest) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *NanoRPCRequest) GetRequestType() NanoRPCRequest_Type {
	if x != nil {
		return x.RequestType
	}
	return NanoRPCRequest_TYPE_UNSPECIFIED
}

func (m *NanoRPCRequest) GetPathOneof() isNanoRPCRequest_PathOneof {
	if m != nil {
		return m.PathOneof
	}
	return nil
}

func (x *NanoRPCRequest) GetPathHash() uint32 {
	if x, ok := x.GetPathOneof().(*NanoRPCRequest_PathHash); ok {
		return x.PathHash
	}
	return 0
}

func (x *NanoRPCRequest) GetPath() string {
	if x, ok := x.GetPathOneof().(*NanoRPCRequest_Path); ok {
		return x.Path
	}
	return ""
}

func (x *NanoRPCRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type isNanoRPCRequest_PathOneof interface {
	isNanoRPCRequest_PathOneof()
}

type NanoRPCRequest_PathHash struct {
	PathHash uint32 `protobuf:"varint,3,opt,name=path_hash,json=pathHash,proto3,oneof"` // FNV-1a hash of path string
}

type NanoRPCRequest_Path struct {
	Path string `protobuf:"bytes,4,opt,name=path,proto3,oneof"` // Human-readable path
}

func (*NanoRPCRequest_PathHash) isNanoRPCRequest_PathOneof() {}

func (*NanoRPCRequest_Path) isNanoRPCRequest_PathOneof() {}

// NanoRPC response message for all server-to-client communication.
// Supports ping responses, RPC results, and subscription updates.
type NanoRPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Matches the request_id from the originating request.
	// For subscription updates, uses the original subscribe request_id.
	RequestId int32 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Type of response being sent.
	ResponseType NanoRPCResponse_Type `protobuf:"varint,2,opt,name=response_type,json=responseType,proto3,enum=NanoRPCResponse_Type" json:"response_type,omitempty"`
	// Status code indicating success or failure.
	// Only meaningful for TYPE_PONG and TYPE_RESPONSE.
	// TYPE_UPDATE messages typically use STATUS_OK.
	ResponseStatus NanoRPCResponse_Status `protobuf:"varint,3,opt,name=response_status,json=responseStatus,proto3,enum=NanoRPCResponse_Status" json:"response_status,omitempty"`
	// Human-readable status message, typically used for errors.
	// Optional field, may be empty for successful operations.
	ResponseMessage string `protobuf:"bytes,4,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	// Response payload data. Usage varies by response type:
	// - TYPE_PONG: unused (should be empty)
	// - TYPE_RESPONSE: RPC result data or subscription confirmation
	// - TYPE_UPDATE: subscription update payload
	// Uses nanopb callback type for zero-copy handling on embedded systems.
	Data []byte `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NanoRPCResponse) Reset() {
	*x = NanoRPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanorpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NanoRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NanoRPCResponse) ProtoMessage() {}

func (x *NanoRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nanorpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NanoRPCResponse.ProtoReflect.Descriptor instead.
func (*NanoRPCResponse) Descriptor() ([]byte, []int) {
	return file_nanorpc_proto_rawDescGZIP(), []int{1}
}

func (x *NanoRPCResponse) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *NanoRPCResponse) GetResponseType() NanoRPCResponse_Type {
	if x != nil {
		return x.ResponseType
	}
	return NanoRPCResponse_TYPE_UNSPECIFIED
}

func (x *NanoRPCResponse) GetResponseStatus() NanoRPCResponse_Status {
	if x != nil {
		return x.ResponseStatus
	}
	return NanoRPCResponse_STATUS_UNSPECIFIED
}

func (x *NanoRPCResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *NanoRPCResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// NanoRPC-specific options for gRPC method definitions.
// Enables declarative request path specification in protobuf service definitions.
// This allows gateway services to translate between NanoRPC and gRPC seamlessly.
type NanoRPCMethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request path for NanoRPC routing.
	// Maps gRPC method calls to NanoRPC paths for gateway translation.
	// Example: "/sensors/temperature" for a GetTemperature RPC method.
	RequestPath *string `protobuf:"bytes,1,opt,name=request_path,json=requestPath,proto3,oneof" json:"request_path,omitempty"`
}

func (x *NanoRPCMethodOptions) Reset() {
	*x = NanoRPCMethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanorpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NanoRPCMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NanoRPCMethodOptions) ProtoMessage() {}

func (x *NanoRPCMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_nanorpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NanoRPCMethodOptions.ProtoReflect.Descriptor instead.
func (*NanoRPCMethodOptions) Descriptor() ([]byte, []int) {
	return file_nanorpc_proto_rawDescGZIP(), []int{2}
}

func (x *NanoRPCMethodOptions) GetRequestPath() string {
	if x != nil && x.RequestPath != nil {
		return *x.RequestPath
	}
	return ""
}

var file_nanorpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*NanoRPCMethodOptions)(nil),
		Field:         5020,
		Name:          "nanorpc",
		Tag:           "bytes,5020,opt,name=nanorpc",
		Filename:      "nanorpc.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional NanoRPCMethodOptions nanorpc = 5020;
	E_Nanorpc = &file_nanorpc_proto_extTypes[0]
)

var File_nanorpc_proto protoreflect.FileDescriptor

var file_nanorpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x61, 0x6e, 0x6f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa0, 0x02, 0x0a, 0x0e, 0x4e, 0x61, 0x6e, 0x6f, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x4e, 0x61, 0x6e, 0x6f, 0x52, 0x50,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x70, 0x61,
	0x74, 0x68, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x08, 0x70, 0x61, 0x74, 0x68, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x92, 0x3f, 0x02, 0x08, 0x32, 0x48, 0x00,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0c, 0x42, 0x05, 0x92, 0x3f, 0x02, 0x18, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x51, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49,
	0x42, 0x45, 0x10, 0x03, 0x42, 0x0c, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6f, 0x6e, 0x65,
	0x6f, 0x66, 0x22, 0xc2, 0x03, 0x0a, 0x0f, 0x4e, 0x61, 0x6e, 0x6f, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x4e,
	0x61, 0x6e, 0x6f, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x40, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x4e, 0x61, 0x6e,
	0x6f, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x05, 0x92, 0x3f,
	0x02, 0x18, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52,
	0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x03, 0x22, 0x7b, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x22, 0x4f, 0x0a, 0x14, 0x4e, 0x61, 0x6e, 0x6f, 0x52,
	0x50, 0x43, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x26, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x3a, 0x53, 0x0a, 0x07, 0x6e, 0x61, 0x6e, 0x6f,
	0x72, 0x70, 0x63, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x9c, 0x27, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4e, 0x61, 0x6e,
	0x6f, 0x52, 0x50, 0x43, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x6e, 0x61, 0x6e, 0x6f, 0x72, 0x70, 0x63, 0x88, 0x01, 0x01, 0x42, 0x27, 0x92,
	0x3f, 0x02, 0x20, 0x00, 0x5a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x63, 0x70, 0x2e, 0x6f,
	0x72, 0x67, 0x2f, 0x6e, 0x61, 0x6e, 0x6f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e,
	0x61, 0x6e, 0x6f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nanorpc_proto_rawDescOnce sync.Once
	file_nanorpc_proto_rawDescData = file_nanorpc_proto_rawDesc
)

func file_nanorpc_proto_rawDescGZIP() []byte {
	file_nanorpc_proto_rawDescOnce.Do(func() {
		file_nanorpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_nanorpc_proto_rawDescData)
	})
	return file_nanorpc_proto_rawDescData
}

var file_nanorpc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nanorpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nanorpc_proto_goTypes = []interface{}{
	(NanoRPCRequest_Type)(0),           // 0: NanoRPCRequest.Type
	(NanoRPCResponse_Type)(0),          // 1: NanoRPCResponse.Type
	(NanoRPCResponse_Status)(0),        // 2: NanoRPCResponse.Status
	(*NanoRPCRequest)(nil),             // 3: NanoRPCRequest
	(*NanoRPCResponse)(nil),            // 4: NanoRPCResponse
	(*NanoRPCMethodOptions)(nil),       // 5: NanoRPCMethodOptions
	(*descriptorpb.MethodOptions)(nil), // 6: google.protobuf.MethodOptions
}
var file_nanorpc_proto_depIdxs = []int32{
	0, // 0: NanoRPCRequest.request_type:type_name -> NanoRPCRequest.Type
	1, // 1: NanoRPCResponse.response_type:type_name -> NanoRPCResponse.Type
	2, // 2: NanoRPCResponse.response_status:type_name -> NanoRPCResponse.Status
	6, // 3: nanorpc:extendee -> google.protobuf.MethodOptions
	5, // 4: nanorpc:type_name -> NanoRPCMethodOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	3, // [3:4] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nanorpc_proto_init() }
func file_nanorpc_proto_init() {
	if File_nanorpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nanorpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NanoRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanorpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NanoRPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanorpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NanoRPCMethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nanorpc_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NanoRPCRequest_PathHash)(nil),
		(*NanoRPCRequest_Path)(nil),
	}
	file_nanorpc_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nanorpc_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_nanorpc_proto_goTypes,
		DependencyIndexes: file_nanorpc_proto_depIdxs,
		EnumInfos:         file_nanorpc_proto_enumTypes,
		MessageInfos:      file_nanorpc_proto_msgTypes,
		ExtensionInfos:    file_nanorpc_proto_extTypes,
	}.Build()
	File_nanorpc_proto = out.File
	file_nanorpc_proto_rawDesc = nil
	file_nanorpc_proto_goTypes = nil
	file_nanorpc_proto_depIdxs = nil
}
